#!/bin/sh

refname="$1"
oldrev="$2"
newrev="$3"

#branch=$(git rev-parse --symbolic --abbrev-ref $refname)
branch=${refname#refs/heads/}

case $branch in
    "master")
        permitted_users=("yutaf")
        for permitted_user in ${permitted_users[@]}; do
            if [ "$permitted_user" = "${REMOTE_USER}" ]; then
                # vim /etc/ssh/sshd_config
                # PermitUserEnvironment yes
                # /etc/init.d/sshd reload
                # ${REMOTE_USER} は /home/git/.ssh/authorized_keys に記述
                exit 0
            fi
        done

        echo "You are not permitted to push to ${branch}"
        exit -1
        ;;
    "develop")
        exit 0
        ;;
    release* | hotfix*)
        exit 0
        ;;
    *)
        # do nothing
        #echo "${branch} is not a branch for push"
        #exit -1
        exit 0
        ;;
esac
